# Generated by Django 3.2.4 on 2021-07-06 13:04

from django.db import migrations, models
import django.db.models.deletion
import onboarding.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('city_name', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=100)),
                ('date_of_booking', models.DateField(max_length=100)),
                ('date_of_onboarding', models.DateField(max_length=100)),
                ('date_of_returning', models.DateField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('city_name', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=100)),
                ('date_of_booking', models.DateField(max_length=100)),
                ('date_of_onboarding', models.DateField(max_length=100)),
                ('date_of_returning', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('kitchen', models.CharField(max_length=200)),
                ('rooms', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=onboarding.models.directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=250)),
                ('phone_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('jobs_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.user_role')),
            ],
        ),
    ]
